title: Amorphous Engineering
description: Tools for hardware teams.
url: "https://amorphous.engineering"
baseurl: ""

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink: /blog/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
